spring:
  application:
    name: security

  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: "4444"

  jpa:
    hibernate:
      ddl-auto: create   # validate / update / create-drop 등 상황에 맞게 선택
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false   # 옵션: OSIV 비활성화 (권장)
